---
title: "coordinates"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{geometries}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#"
)
```

```{r setup}
library(geometries)
library(Rcpp)
```


```r
#include "geometries/coordinates/dimensions.hpp"
```


```{r}

cppFunction(
  depends = "geometries"
  , includes = '#include "geometries/shapes/shapes.hpp"'
  , code = '
    SEXP polygon( SEXP df, SEXP geometry_cols, SEXP line_id ) {
      return geometries::shapes::to_listMat( df, geometry_cols, line_id );
    }
  '
)

```

### Geometry Dimension

Counts the number of coordinates, the dimension, and the level of nesting.


```{r}

## Count Coordinates
##
## either counts the number of coordinates in a given geometry,
cppFunction(
  depends = 'geometries'
  , includes = '#include "geometries/coordinates/dimensions.hpp"'
  , code = '
    Rcpp::IntegerVector geometry_dimension( SEXP x ) {
      R_xlen_t count = 0;
      R_xlen_t dimension = 0;
      R_xlen_t nest = 0;
      geometries::coordinates::geometry_dimension( x, count, dimension, nest );
      Rcpp::IntegerVector iv(3);
      iv[0] = count;
      iv[1] = dimension;
      iv[2] = nest;
      return iv;
    }
  '
)

df <- data.frame(
  x = 1:10
  , y = 10:1
  , z = 21:30
  , m = 30:21
  , val = letters[1:10]
  , id = c( rep(1,5), rep(2,5) )
)

poly <- polygon( df, c("x","y"), c("id") )

geometry_dimension( poly )
```


### Coordinate Dimensions

```{r}

## Coordinate indices
##
## gives the start and end indices of geometries
cppFunction(
  depends = 'geometries'
  , includes = '#include "geometries/coordinates/dimensions.hpp"'
  , code = '
    Rcpp::IntegerMatrix geometry_dimensions( SEXP x ) {
      return geometries::coordinates::geometry_dimensions( x );
    }
  '
)

x <- 1:2

geometry_dimensions( x )

m <- matrix(1:6, ncol = 2)

geometry_dimensions( m )

l <- list(
  matrix(1:20, ncol = 2 )
  , matrix(1:6, ncol = 2)
  , matrix(1:10, ncol = 2)
)

geometry_dimensions( l )

l <- list( l )
geometry_dimensions( l )


```


