# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_calculate_bbox <- function(x, geometry_cols) {
    .Call(`_geometries_rcpp_calculate_bbox`, x, geometry_cols)
}

rcpp_close_matrix <- function(x) {
    .Call(`_geometries_rcpp_close_matrix`, x)
}

rcpp_other_columns <- function(x, id_cols, id_col2, id_col3) {
    .Call(`_geometries_rcpp_other_columns`, x, id_cols, id_col2, id_col3)
}

rcpp_geometry_dimensions <- function(geometries) {
    .Call(`_geometries_rcpp_geometry_dimensions`, geometries)
}

rcpp_coordinates <- function(geometries) {
    .Call(`_geometries_rcpp_coordinates`, geometries)
}

rcpp_make_geometries <- function(x, id_cols, geometry_cols, attributes, close) {
    .Call(`_geometries_rcpp_make_geometries`, x, id_cols, geometry_cols, attributes, close)
}

rcpp_id_positions <- function(x, i) {
    .Call(`_geometries_rcpp_id_positions`, x, i)
}

rcpp_rleid <- function(df, ids) {
    .Call(`_geometries_rcpp_rleid`, df, ids)
}

rcpp_rleid_indices <- function(x) {
    .Call(`_geometries_rcpp_rleid_indices`, x)
}

.test_attributes <- function(obj, attributes) {
    invisible(.Call(`_geometries_test_attributes`, obj, attributes))
}

.test_to_geometry_matrix_cols <- function(x, cols) {
    .Call(`_geometries_test_to_geometry_matrix_cols`, x, cols)
}

.test_to_geometry_matrix_cols_names <- function(x, cols, keep_names) {
    .Call(`_geometries_test_to_geometry_matrix_cols_names`, x, cols, keep_names)
}

.test_to_geometry_matrix_single <- function(x) {
    .Call(`_geometries_test_to_geometry_matrix_single`, x)
}

tm <- function(x) {
    .Call(`_geometries_tm`, x)
}

.test_sexp_col_int <- function(x, v) {
    .Call(`_geometries_test_sexp_col_int`, x, v)
}

.test_sexp_col_names <- function(x) {
    .Call(`_geometries_test_sexp_col_names`, x)
}

.test_sexp_n_col <- function(x) {
    .Call(`_geometries_test_sexp_n_col`, x)
}

.test_sexp_n_row <- function(x) {
    .Call(`_geometries_test_sexp_n_row`, x)
}

.test_sexp_length <- function(x) {
    .Call(`_geometries_test_sexp_length`, x)
}

.test_column_check <- function(x, cols) {
    invisible(.Call(`_geometries_test_column_check`, x, cols))
}

test_other_columns_impl <- function() {
    .Call(`_geometries_test_other_columns_impl`)
}

.test_other_columns <- function(x, y, z) {
    .Call(`_geometries_test_other_columns`, x, y, z)
}

.test_column_positions <- function(x, cols) {
    .Call(`_geometries_test_column_positions`, x, cols)
}

.test_make_dataframe <- function(lst, n_rows, col_names) {
    .Call(`_geometries_test_make_dataframe`, lst, n_rows, col_names)
}

.test_unique_ids <- function(x, id_col) {
    .Call(`_geometries_test_unique_ids`, x, id_col)
}

.test_unique_sort <- function(x) {
    .Call(`_geometries_test_unique_sort`, x)
}

.test_as_list <- function(x) {
    .Call(`_geometries_test_as_list`, x)
}

.tests <- function() {
    .Call(`_geometries_tests`)
}

rcpp_concatenate_vectors <- function(vec_1, vec_2) {
    .Call(`_geometries_rcpp_concatenate_vectors`, vec_1, vec_2)
}

rcpp_column_positions <- function(m, cols) {
    .Call(`_geometries_rcpp_column_positions`, m, cols)
}

rcpp_where_is <- function(to_find, sv) {
    .Call(`_geometries_rcpp_where_is`, to_find, sv)
}

rcpp_get_ids <- function(x, id_col) {
    .Call(`_geometries_rcpp_get_ids`, x, id_col)
}

