# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_calculate_bbox <- function(x, geometry_cols) {
    .Call(`_geometries_rcpp_calculate_bbox`, x, geometry_cols)
}

rcpp_geometry_dimensions <- function(geometries) {
    .Call(`_geometries_rcpp_geometry_dimensions`, geometries)
}

rcpp_get_vec <- function(x, cols) {
    .Call(`_geometries_rcpp_get_vec`, x, cols)
}

rcpp_to_mat <- function(x, cols) {
    .Call(`_geometries_rcpp_to_mat`, x, cols)
}

rcpp_get_list_mat <- function(x, cols, id) {
    .Call(`_geometries_rcpp_get_list_mat`, x, cols, id)
}

rcpp_geometry_coordinates <- function(geometry) {
    .Call(`_geometries_rcpp_geometry_coordinates`, geometry)
}

rcpp_coordinates <- function(geometries) {
    .Call(`_geometries_rcpp_coordinates`, geometries)
}

rcpp_from_listMat <- function(lst) {
    .Call(`_geometries_rcpp_from_listMat`, lst)
}

.tests <- function() {
    .Call(`_geometries_tests`)
}

